services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.4.0'
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - unified-network

  kafka:
    image: 'confluentinc/cp-kafka:7.4.0'
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"   # Puerto interno (para comunicación entre contenedores)
      - "9093:9093"   # Puerto externo (para clientes que se conecten usando localhost)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Definimos dos listeners: uno interno (PLAINTEXT) y uno externo (EXTERNAL)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      # El advertised listener para el interno se usa entre contenedores, y para el externo se utiliza desde el host.
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - unified-network

networks:
  unified-network:
    external: true
    name: unified-network